# Trace and Determinant

If you are done with all the previous challenges, you can try these katas that can be found on Codewars:
- [Calculate the trace of a square matrix](https://www.codewars.com/kata/matrix-trace/train/python)
- [Write a function that accepts a square matrix (N x N 2D array) and returns the determinant of the matrix.](https://www.codewars.com/kata/matrix-determinant/train/python)

In [1]:
import numpy as np

## Trace

Calculate the trace of a square matrix. 

* A square matrix has `n` rows and `n` columns, where `n` is any integer > 0. 
* The entries of the matrix can contain any number of integers. 

The function should return the calculated trace of the matrix, or None if the array is empty or not square. 

The trace of an n-by-n square matrix A is defined to be the sum of the elements on the main diagonal (the diagonal from the upper left to the lower right) of A.

You can read more about the trace of a matrix at these sources:
* http://en.wikipedia.org/wiki/Trace_(linear_algebra)
* http://mathworld.wolfram.com/MatrixTrace.html

### Warm-up

Let's create now a square matrix $ A = \begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6\\
    7 & 8 & 9
\end{bmatrix}$

In [2]:
A = np.array([
                [1,2,3],
                [4,5,6],
                [7,8,9]
            ])

print(f"""
{A},

{A.shape = }
{A.dtype = },
""")


[[1 2 3]
 [4 5 6]
 [7 8 9]],

A.shape = (3, 3)
A.dtype = dtype('int64'),



Compute its trace, which is the sum of its diagonal elements.

In [3]:
diagonal_elements_of_A = [A[k][k] for k in range(A.shape[0])]
trace_of_A = np.sum(diagonal_elements_of_A)
trace_of_A2 = np.sum(np.diag(A))


print(f"""
{diagonal_elements_of_A = }
{trace_of_A = }
{trace_of_A2 = }
""")



diagonal_elements_of_A = [1, 5, 9]
trace_of_A = 15
trace_of_A2 = 15



### The `trace` function

Compute now the trace function which returns the trace of a matrix, checking first that it's a square matrix

In [11]:
def trace(matrix: np.array) -> float:
    # Empty matrix ?
    if len(matrix) == 0:
        return "it is an empty matrix"
    
    # Square matrix ?
    if matrix.shape[0] != matrix.shape[1]:
        return "It is not a squared matrix"

    # Returning the sum of the elements on the diagonal in one line of code
    return np.sum(np.diag(matrix))


In [12]:
trace(A)

15

## Determinant 

[Determinant](https://en.wikipedia.org/wiki/Determinant) are extremely important concepts in linear algebra. 

To start with, _a matrix is invertible if and only if its determinant is different from 0_  

It's pretty useful to measure _how close to being non-invertible_ a matrix is (in a quantifiable way!)

But that's not all of it: watch this <a href="https://www.youtube.com/watch?v=Ip3X9LOh2dk">10-min Youtube video </a> to get an intuition about what is a determinant and why it's important

Your goal is to **create a function that manually compute the determinant of any matrix** (squared or not). It's a hard question, so, good luck! 

----
<u>**Hints:**</u>

Here are some properties of a determinant that could help you build the function
* The determinant of an empty matrix is 0
* The determinant of a $ 1 \times 1 $ matrix is equal to its single coefficient
* The determinant of a $ 2 \times 2 $ matrix $\begin{bmatrix} a & b\\ c & d \end{bmatrix}$ is equal to $ad - bc$
* The determinant of a $ 3 \times 3 $ matrix can be computed recursively based on the $ 2 \times 2 $ `minor determinants`, alternating + and minus signs
$$\begin{aligned}{\begin{vmatrix}a&b&c\\d&e&f\\g&h&i\end{vmatrix}}&=a\,{\begin{vmatrix}e&f\\h&i\end{vmatrix}}-b\,{\begin{vmatrix}d&f\\g&i\end{vmatrix}}+c\,{\begin{vmatrix}d&e\\g&h\end{vmatrix}}\end{aligned}$$
* etc...

Your function should therefore be a **`recursive function`** (a function that calls itself!)

In [16]:
def determinant(matrix: np.array) -> float:   
    # Empty Matrix  ?
    if len(matrix) == 0:
        return None
    
    # Square matrix ?
    if matrix.shape[0] != matrix.shape[1]:
        return None

    # Easy cases
    
    if len(matrix) == 1:
        return matrix[0][0]
    
    if len(matrix) == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    
    # General Case
    
    det = 0
    
    for k in range(len(matrix)):        
        submatrix = np.delete(np.delete(matrix, k, axis=1), 0, axis=0)
        det_minor = determinant(submatrix)

        # adding the "minor determinants" to the global determinant
        det += (1 if k % 2 == 0 else -1) * matrix[0][k] * det_minor
    
    return det